services:
  # ─────────── REDIS (cola Celery) ───────────
  - type: redis
    name: leo-trainer-redis
    plan: starter

  # ─────────── BACKEND FLASK ───────────
  - type: web
    name: leo-backend
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      # VARIABLES DE PRODUCCIÓN (ya existen en tu panel → sync: false)
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      # NUEVAS VARIABLES S3
      - key: AWS_S3_BUCKET_NAME
        value: leocoach
      - key: AWS_S3_REGION_NAME
        value: us-east-1
      # CONEXIÓN REDIS COMPARTIDA
      - key: REDIS_URL
        fromService:
          name: leo-trainer-redis
          type: redis
          property: connectionString

  # ─────────── CELERY WORKER ───────────
  - type: worker
    name: leo-trainer-worker
    env: docker
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: celery -A celery_worker.celery_app worker --loglevel=info -c 5
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET_NAME
        value: leocoach
      - key: AWS_S3_REGION_NAME
        value: us-east-1
      - key: REDIS_URL
        fromService:
          name: leo-trainer-redis
          type: redis
          property: connectionString
